metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Modules système
metricbeat.modules:
  # Module système
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - filesystem
      - fsstat
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5

  # Module Docker
  - module: docker
    period: 10s
    hosts: ["unix:///var/run/docker.sock"]
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network

# Processeurs
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata: ~
  - add_fields:
      target: ''
      fields:
        environment: staging
        application: si-releves

# Output vers Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "metricbeat-%{+yyyy.MM.dd}"

# Setup
setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644
